server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SQL_HOST}tomsbakery
    username: ${SQL_TK_USER}
    password: ${SQL_TK_PW}
  kafka:
    bootstrap-servers: localhost:9092