server:
  port: 8081

spring:
  application:
    name: orders
  kafka:
    bootstrap-servers: localhost:9092
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: ${SQL_HOST}tomsbakeryorders
#    username: ${SQL_TK_USER}
#    password: ${SQL_TK_PW}