server:
  port: 8081

spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: broker:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: toms.bakery.test@gmail.com
    password: ${TOMSBAKERY_EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true