stripe:
  public:
    key: ${STRIPE_PUBLIC_KEY}
  secret:
    key: ${STRIPE_SECRET_KEY}
  
#########
# MYSQL
#########
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SQL_HOST}tomsbakery
    username: ${SQL_TK_USER}
    password: ${SQL_TK_PW}
  
#########
# HTTPS Configuration
#########
  # Server web port
#server:
#  port: 8443
#  # Enable HTTPS support (only accept HTTPS requests)
#  ssl:
#    enabled: true
#    # Alias that identifies the key in the key store
#    key-alias: tomsbakery
#    # Keystore location
#    key-store: classpath:tomsbakery-keystore.p12
#    # Keystore password
#    key-store-password: ${TOMSBAKERY_HTTPS_PW}
#    # Keystore format
#    key-store-type: PKCS12